package com.emergent.doom.factorization;

import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import java.util.Comparator;

/**
 * Factory for creating FactorCell populations with strategy distribution.
 *
 * <p><strong>PURPOSE:</strong> Generate chimeric factor candidate arrays where
 * each cell carries a candidate integer and a factor-finding strategy. Strategies
 * are embedded in cells (not positions) following Levin-aligned semantics.</p>
 *
 * <p><strong>DESIGN PATTERN:</strong> Mirrors SortingCellFactory but for factorization
 * domain. Uses CandidateGenerator for strategy-specific candidate generation.</p>
 *
 * <p><strong>USAGE EXAMPLE:</strong></p>
 * <pre>
 * FactorCellFactory factory = new FactorCellFactory(42L);  // Seeded for reproducibility
 * 
 * Map&lt;FactorStrategy, Double&gt; distribution = Map.of(
 *     FactorStrategy.SMALL_PRIMES, 0.33,
 *     FactorStrategy.FERMAT_NEAR_SQRT, 0.33,
 *     FactorStrategy.RANDOM_SAMPLE, 0.34
 * );
 * 
 * List&lt;FactorCell&gt; cells = factory.createCells(143, 50, distribution);
 * </pre>
 */
public class FactorCellFactory {
    
    private final Random random;
    
    /**
     * Create factory with seeded random for reproducibility.
     *
     * <p><strong>PURPOSE:</strong> Enable deterministic experiments with fixed seeds.</p>
     *
     * @param seed random seed
     */
    public FactorCellFactory(long seed) {
        this.random = new Random(seed);
    }
    
    /**
     * Create factory with unseeded random.
     */
    public FactorCellFactory() {
        this.random = new Random();
    }
    
    /**
     * Create chimeric factor cell population with strategy distribution.
     *
     * <p><strong>PURPOSE:</strong> Generate N cells with specified strategy percentages,
     * each carrying a candidate integer generated by its assigned strategy.</p>
     *
     * <p><strong>INPUTS:</strong></p>
     * <ul>
     *   <li>target - the semiprime N being factored</li>
     *   <li>size - number of cells to create</li>
     *   <li>distribution - map of strategy to percentage (must sum to ~1.0)</li>
     * </ul>
     *
     * <p><strong>PROCESS:</strong></p>
     * <ol>
     *   <li>Validate distribution sums to ~1.0</li>
     *   <li>Calculate count for each strategy based on percentage</li>
     *   <li>Generate candidates using CandidateGenerator for each strategy</li>
     *   <li>Create FactorCells with candidates and embedded strategies</li>
     *   <li>Shuffle cell order for random spatial distribution</li>
     * </ol>
     *
     * <p><strong>OUTPUTS:</strong> List of FactorCells with embedded strategies</p>
     *
     * <p><strong>CRITICAL:</strong> Strategies are assigned to cells ONCE and travel
     * WITH cells during swaps, enabling emergent clustering.</p>
     *
     * @param target the semiprime N being factored
     * @param size number of cells to create
     * @param distribution strategy distribution (percentages must sum to ~1.0)
     * @return list of factor cells with embedded strategies
     * @throws IllegalArgumentException if distribution invalid
     */
    public List<FactorCell> createCells(
            int target,
            int size,
            Map<FactorStrategy, Double> distribution) {
        
        // Validate distribution
        double sum = distribution.values().stream().mapToDouble(Double::doubleValue).sum();
        if (Math.abs(sum - 1.0) > 0.01) {
            throw new IllegalArgumentException(
                "Distribution percentages must sum to 1.0, got: " + sum
            );
        }
        
        // Calculate count for each strategy
        Map<FactorStrategy, Integer> counts = new HashMap<>();
        int remaining = size;
        
        // Sort entries by strategy name for deterministic ordering
        List<Map.Entry<FactorStrategy, Double>> entries = new ArrayList<>(distribution.entrySet());
        entries.sort(Comparator.comparing(e -> e.getKey().name()));
        
        for (int i = 0; i < entries.size(); i++) {
            Map.Entry<FactorStrategy, Double> entry = entries.get(i);
            int count;
            if (i == entries.size() - 1) {
                // Last strategy gets remaining to avoid rounding errors
                count = remaining;
            } else {
                count = (int) Math.round(entry.getValue() * size);
                remaining -= count;
            }
            counts.put(entry.getKey(), count);
        }
        
        // Generate candidates for each strategy
        List<FactorCell> cells = new ArrayList<>();
        int position = 0;
        
        for (Map.Entry<FactorStrategy, Integer> entry : counts.entrySet()) {
            FactorStrategy strategy = entry.getKey();
            int count = entry.getValue();
            
            // Generate candidates using strategy-specific generator
            List<Integer> candidates = generateCandidatesForStrategy(strategy, target, count);
            
            // Create FactorCells with candidates and strategy
            for (Integer candidate : candidates) {
                cells.add(new FactorCell(candidate, target, strategy, position));
                position++;
            }
        }
        
        // Shuffle cells for random spatial distribution
        // (Strategies embedded in cells, so shuffling distributes strategies randomly)
        Collections.shuffle(cells, random);
        
        // Update positions after shuffle
        for (int i = 0; i < cells.size(); i++) {
            cells.get(i).updatePositionTo(i);
        }
        
        return cells;
    }
    
    /**
     * Generate candidates using strategy-specific logic.
     *
     * <p><strong>PURPOSE:</strong> Delegate to CandidateGenerator based on strategy.</p>
     *
     * @param strategy the factor-finding strategy
     * @param target the semiprime N
     * @param count number of candidates to generate
     * @return list of candidate integers
     */
    private List<Integer> generateCandidatesForStrategy(
            FactorStrategy strategy,
            int target,
            int count) {
        
        switch (strategy) {
            case SMALL_PRIMES:
                return CandidateGenerator.generateSmallPrimes(target, count, random);
                
            case FERMAT_NEAR_SQRT:
                return CandidateGenerator.generateFermatNearSqrt(target, count, random);
                
            case RANDOM_SAMPLE:
                return CandidateGenerator.generateRandomSample(target, count, random);
                
            default:
                throw new IllegalArgumentException("Unknown strategy: " + strategy);
        }
    }
}
